// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xsinxmwigetbybeybbkp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhzaW54bXdpZ2V0YnliZXliYmtwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzc2NTM5MTAsImV4cCI6MjA1MzIyOTkxMH0.9Dg-vnFWzx1n2Asg-XawOhmaPk2gsT7RurFh-VjJP7I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);